site_name: PsychoAnalyze
site_url: https://github.com/schlich/psychoanalyze
theme:
    name: readthedocs
plugins:
 - search
 - mkdocstrings:
    watch:
    - psychoanalyze
 - mkdocs-jupyter:
    include_source: True
repo_url: https://github.com/schlich/psychoanalyze
edit_uri: edit/main/docs/