site_name: PsychoAnalyze
site_url: https://psychoanalyze.io
theme:
    name: material
plugins:
 - search
 - mkdocstrings:
repo_url: https://github.com/psychoanalyze/psychoanalyze
edit_uri: edit/main/docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
extra_javascript:
 - https://cdn.plot.ly/plotly-2.12.1.min.js
 - docs/require.js
watch:
 - psychoanalyze
 - dashboard
 - tests
