site_name: PsychoAnalyze
site_url: https://github.com/schlich/psychoanalyze
theme:
    name: material
plugins:
 - search
 - mkdocstrings:
    watch:
    - psychoanalyze
repo_url: https://github.com/schlich/psychoanalyze
edit_uri: edit/main/docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
extra_javascript:
 - https://cdn.plot.ly/plotly-2.12.1.min.js
 - docs/require.js