site_name: PsychoAnalyze
site_url: https://github.com/schlich/psychoanalyze
theme:
    name: readthedocs
plugins:
 - search
 - gen-files:
    scripts:
    - docs/gen_ref_pages.py
 - mkdocstrings:
    watch:
    - psychoanalyze
 - mkdocs-jupyter:
    include_source: True
nav:
 - Notebook: notebook.ipynb
repo_url: schlich/psychoanalyze