site_name: PsychoAnalyze
site_url: https://psychoanalyze.io
theme:
  name: material
  logo: assets/logo_bgwhite.png
  favicon: assets/logo_bgwhite.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_submodules: true
          members_order: source
repo_url: https://github.com/psychoanalyze/psychoanalyze
edit_uri: edit/main/docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      title: On this page
extra_javascript:
  - https://cdn.plot.ly/plotly-2.12.1.min.js
  - docs/require.js
watch:
  - psychoanalyze
  - tests
nav:
  - 'index.md'
  - 'dashboard.md'
  - 'api.md'
  - 'CONTRIBUTING.md'
  - 'tests.md'
  - Notebooks: '/notebooks/'
