project:
  type: website

website:
  title: "Psychophysics: The Fundamentals"
  navbar:
    left:
      - href: index.qmd
        text: Chapter 1
      - href: chapter2.qmd
        text: Chapter 2
      - href: chapter3.qmd
        text: Chapter 3
      - href: chapter4.qmd
        text: Chapter 4
      - href: chapter5.qmd
        text: Chapter 5
      - href: chapter6.qmd
        text: Chapter 6
      - href: chapter7.qmd
        text: Chapter 7

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



