version: '3.8'
services:

  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:0-3.11
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  pymc:
    image: mcr.microsoft.com/devcontainers/miniconda
