name: docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy docs via GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      
      - name: Install Poetry
        run: pipx install poetry
      
      - name: Export requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements.txt