version: 2

models:
  - name: sessions
    description: A session consists of a full day of trials for a given subject.


exposures:
  - name: longitudinal_thresholds
    label: Longitudinal Thresholds
    type: dashboard
    owner: 
      name: PsychoAnalyze
      email: support@psychoanalyze.io


sources:
  - name: Simulation
    tables:
      - name: Trials
        meta:
          external_location: 'data/test/trials.csv'
        columns:
          - name: TrialID
            type: int
          - name: Outcome
            type: int
      - name: Outcomes
        meta:
          external_location: 'data/test/outcomes.csv'