version: 2

models:
  - name: sessions
    description: A session consists of a full day of trials for a given subject.


sources:
  - name: Simulation
    tables:
      - name: Trials
        meta:
          external_location: 'data/test/trials.csv'
        columns:
          - name: TrialID
            type: int
          - name: Outcome
            type: int