version: 2

sources:
  - name: Simulation
    tables:
      - name: Trials
        meta:
          external_location: 'data/test/trials.csv'
        columns:
          - name: TrialID
            type: int
          - name: Outcome
            type: int